### ISSUE TITLE
openjdk8-jvmci-21.3-b05 used in GraalVM CE 21.3.0 missing from releases

### ISSUE THREAD

**Issue by zakkak** [graalvm/graal-jvmci-8#11]
Running mx fetch-jdk in graal's tag https://github.com/oracle/graal/releases/tag/vm-21.3.0 results in:

```
Error retrieving https://github.com/graalvm/graal-jvmci-8/releases/download/jvmci-21.3-b05/openjdk-8u302+06-jvmci-21.3-b05-linux-amd64.tar.gz.sha1: HTTP Error 404: Not Found
```

**Comment by dougxc** [comment]
@marwan-hallaoui please take care of this.

**Comment by fniephaus** [comment]
Same here: [`jvmci-21.3-b05`](https://github.com/graalvm/graal-jvmci-8/releases/tag/jvmci-21.3-b05) exists but has no assets.

**Comment by marwan-hallaoui** [comment]
done

**Comment by zakkak** [comment]
Thank you @marwan-hallaoui !
