### ISSUE TITLE
Linux 5.0 support

### ISSUE THREAD

**Issue by oroppas** [graalvm/graal-jvmci-8#3]
Arch Linux moved to kernel 5.0
Would it be possible to support the latest kernel?

**Comment by dougxc** [comment]
What would that entail? This repo is a fork of http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot so if the support you're requesting is added there, then it will be in graal-jvmci-8.

**Comment by oroppas** [comment]
Gotcha. Apology for the noise.
