### ISSUE TITLE
Tagging jvmci-19-b01

### ISSUE THREAD

**Issue by flortsch** [graalvm/graal-jvmci-8#5]
On https://github.com/graalvm/openjdk8-jvmci-builder/releases I saw that graal-jvmci-8 has been built for jvmci-19-b01 but unfortunately I can't see any jvmci-19-b01 tag in this repository. I would like to build graal-jvmci-8 myself for jvmci-19-b01 and aarch64.

**Comment by ansalond** [comment]
Hi @flortsch, thanks for the report. I pushed the `release/jvmci/19` branch, which contains the `jvmci-19-b01` tag. Sorry for the trouble.
