### ISSUE TITLE
Please release jvmci-20.3-b06

### ISSUE THREAD

**Issue by sdeleuze** [graalvm/graal-jvmci-8#7]
Please make a proper release for [jvmci-20.3-b06](https://github.com/graalvm/graal-jvmci-8/releases/tag/jvmci-20.3-b06) since the related artifacts are needed to build GraalVM 20.3.0.

**Comment by dougxc** [comment]
They are now uploaded. Same goes for the 11 and 15 releases of jvmci-20.3-b06. Sorry for the delay.

**Comment by sdeleuze** [comment]
Thanks!
